export const REQUEST_ALL_BREEDS = "REQUEST_ALL_BREEDS"
export const REQUEST_BREED = "REQUEST_BREED"
export const REQUEST_ALL_SUB_BREEDS = "REQUEST_ALL_SUB_BREEDS"
export const REQUEST_SUB_BREED = "REQUEST_SUB_BREED"
